remote_theme: pages-themes/cayman@v0.2.0
title: Engineering Ladders
description: A framework for Engineering Managers
plugins:
- jekyll-remote-theme 
collections:
  es:
    output: true
navigation:
  - name: "Home"
    link: "/"
  - name: "Inicio"
    link: "/es/"
